# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f5c102d3f5de6ceeb908527f99c83f9e895d7ad0dc2765a27397faf5485cdcc206a1a7d7948f92da870eaa55c488d10579f2c442190471414039335df912de1

test:
  secret_key_base: 3a10d6683146b8ccce1dc9973f15fead6372babdc5a588be31aaa888fcfc93bd9f23ba1026cfe6fef75a1e736070003cc993927612102be3d35a06d16b63760a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
